Feature/1 improve errors and tooltips
cloudogu/adf-widget-scm pull request #2
Opened 2021-06-17 06:19 UTC by sklein94

Resolve #1

2021-06-23 09:15 UTC, JBartscher commented
# Summary

Added tooltips for configuration of widgets. It was mostly reusable code from the github widgets.
However there was a problem with the "required" attribute in the 'SCM Markdown Content
'-widget. If this attribute was attached to the <selects> the form could no longer be submitted. Therefore, the "required" attribute was only attached to the markdown-path field, but now the markdown-path is only displayed if a branch is available (per angular condition). Ergo, a repository has been selected.
The tooltip message was also extended a bit with more tips on how to fill the fields.

2021-06-23 14:28 UTC, Phil-Ah requested changes
Good work adding all the tooltips. Some may be expressed more clearly. See comments below.

2021-06-23 14:28 UTC, Phil-Ah commented on .gitignore
> +.idea/
Please do not push the .idea -folder.

2021-06-23 14:28 UTC, Phil-Ah commented on dist/adf-widget-scm.js
> +$templateCache.put("{widgetsPath}/scm/src/edit/edit.html","<form role=form><div class=form-group><label for=repository>Repository</label> <span class=\"grey glyphicon glyphicon-info-sign ng-scope\" t
Is the URL of the Jenkins server the right default message?

2021-06-23 14:28 UTC, Phil-Ah commented on dist/adf-widget-scm.js
> +$templateCache.put("{widgetsPath}/scm/src/markdownPreview/edit.html","<form role=form><div class=form-group><p><label for=repository>Repository</label> <span class=\"grey glyphicon glyphicon-info-sig
Is the URL of the Jenkins server the right default message?
Please refer to voice & tone when writing messages. “A valid path to a markdown file must be stored here” might be rewritten to “Enter the path to a markdown file”.
Add information if the format of the path has to follow a special format (no leading / for example)

2021-06-23 14:28 UTC, Phil-Ah commented on dist/adf-widget-scm.js
> +$templateCache.put("{widgetsPath}/scm/src/markdownPreview/view.html","<style>\n  div.markdownContent{\n    overflow: auto;\n    width: 100%;\n  }\n</style><div class=\"alert alert-info\" ng-if=\"vm.f
“Configure a specific file”

2021-06-23 14:28 UTC, Phil-Ah commented on dist/adf-widget-scm.js
> +    $scope.pathToMarkdownTooltip = $sce.trustAsHtml('The path where the Markdown file can be found within the repository (e.g. <b>docs/README.md</b>). Note that the path is case sensitive. For files
“Enter the path to the Markdown file with a leading slash. The path is case sensitive. Files in the root dir start <b>without</b> a leading slash.

2021-06-23 14:28 UTC, Phil-Ah commented on dist/adf-widget-scm.js
> +    $scope.repositoryTooltip = $sce.trustAsHtml('Select the repository which is used to provide data.');
“Select a repository”

2021-06-23 14:28 UTC, Phil-Ah commented on src/edit/edit.html
> +    <span class="grey glyphicon glyphicon-info-sign ng-scope" tabindex="0" ng-focus="repositoryTooltipIsOpen = !repositoryTooltipIsOpen" tooltip-trigger="outsideClick" tooltip-is-open="repositoryTool
Is the URL of the Jenkins server the right default message?

2021-06-23 14:28 UTC, Phil-Ah commented on src/edit/simpleEditController.js
> +    $scope.repositoryTooltip = $sce.trustAsHtml('Select the repository which is used to provide data.');
“Select a repository”

2021-06-23 14:28 UTC, Phil-Ah commented on src/markdownPreview/edit.html
> +            aria-label="A valid URL to your Jenkins server must be stored here"></span>
Is the URL of the Jenkins server the right default message?

2021-06-23 14:28 UTC, Phil-Ah commented on src/markdownPreview/edit.html
> +            aria-label="A valid URL to your Jenkins server must be stored here"></span>
Is the URL of the Jenkins server the right default message?

2021-06-23 14:28 UTC, Phil-Ah commented on src/markdownPreview/markdownPreviewEdit.js
> +    $scope.repositoryTooltip = $sce.trustAsHtml('Select the repository which stores the desired Markdown.');
Please refer to voice & tone when writing messages. “A valid path to a markdown file must be stored here” might be rewritten to “Enter the path to a markdown file”.
Add information if the format of the path has to follow a special format (no leading / for example)

2021-06-23 14:28 UTC, Phil-Ah commented on src/markdownPreview/edit.html
> +            tooltip-placement="top" aria-label="A valid path to a markdown file must be stored here"></span>
Please refer to voice & tone when writing messages. “A valid path to a markdown file must be stored here” might be rewritten to “Enter the path to a markdown file”.
Add information if the format of the path has to follow a special format (no leading / for example)

2021-06-23 14:28 UTC, Phil-Ah commented on src/markdownPreview/markdownPreviewEdit.js
> +    $scope.branchTooltip = $sce.trustAsHtml('Select the branch on which the desired Markdown file can be found.');
Refer to prior suggestions for wording.

2021-06-29 11:12 UTC, mbehlendorf commented on src/edit/simpleEditController.js
> +    $scope.repositoryTooltip = $sce.trustAsHtml('Select the repository.');
Maybe use parseAsHtml?

2021-06-29 11:14 UTC, mbehlendorf commented on src/markdownPreview/edit.html
> +      <span class="grey glyphicon glyphicon-info-sign ng-scope" tabindex="0"
Why using 2 variables here? `tooltipIsOpenRepo` and `repositoryTooltipIsOpen`
Some attributes are defined 2 times: e.g. `tooltip-is-open`

2021-06-29 11:15 UTC, mbehlendorf commented on src/markdownPreview/edit.html
> +      <span class="grey glyphicon glyphicon-info-sign ng-scope" tabindex="0"
see above

2021-06-29 11:15 UTC, mbehlendorf commented on src/markdownPreview/edit.html
> +      <span class="grey glyphicon glyphicon-info-sign ng-scope" tabindex="0"
see above

2021-06-29 11:16 UTC, mbehlendorf commented on src/markdownPreview/markdownPreviewEdit.js
> +    $scope.repositoryTooltip = $sce.trustAsHtml('Select the repository. If none is shown, check your scm configuration.');
see above

2021-06-29 14:13 UTC, closed without merging